import {
  brandSet,
  cifBr,
  cifEs,
  cifFr,
  cifIn,
  cifPl,
  cifUs,
  cilAccountLogout,
  cilActionUndo,
  cilAlignCenter,
  cilAlignLeft,
  cilAlignRight,
  cilApplications,
  cilApplicationsSettings,
  cilArrowBottom,
  cilArrowRight,
  cilArrowTop,
  cilBadge,
  cilBasket,
  cilBell,
  cilBold,
  cilBook,
  cilBookmark,
  cilBug,
  cilCalculator,
  cilCalendar,
  cilCast,
  cilChart,
  cilChartPie,
  cilCheck,
  cilChevronCircleLeftAlt,
  cilChevronDoubleLeft,
  cilChevronDoubleRight,
  cilChevronLeft,
  cilChevronRight,
  cilCloudDownload,
  cilCode,
  cilCommentSquare,
  cilContrast,
  cilCreditCard,
  cilCursor,
  cilDelete,
  cilDescription,
  cilDollar,
  cilDrop,
  cilEnvelopeClosed,
  cilEnvelopeOpen,
  cilFeaturedPlaylist,
  cilFile,
  cilGamepad,
  cilGrid,
  cilHeart,
  cilHome,
  cilImage,
  cilInbox,
  cilIndentDecrease,
  cilIndentIncrease,
  cilInfo,
  cilItalic,
  cilJustifyCenter,
  cilLanguage,
  cilLaptop,
  cilLayers,
  cilLibraryAdd,
  cilLink,
  cilLinkBroken,
  cilList,
  cilListNumbered,
  cilLocationPin,
  cilLockLocked,
  cilMagnifyingGlass,
  cilMap,
  cilMediaPlay,
  cilMediaRecord,
  cilMenu,
  cilMobile,
  cilMoon,
  cilMovie,
  cilNoteAdd,
  cilNotes,
  cilOptions,
  cilPaperclip,
  cilPaperPlane,
  cilPen,
  cilPencil,
  cilPeople,
  cilPowerStandby,
  cilPrint,
  cilPuzzle,
  cilReportSlash,
  cilRouter,
  cilSave,
  cilSearch,
  cilSend,
  cilSettings,
  cilShare,
  cilShareAll,
  cilShareBoxed,
  cilShieldAlt,
  cilSpeech,
  cilSpeedometer,
  cilSpreadsheet,
  cilStar,
  cilSun,
  cilSync,
  cilToggleOff,
  cilToggleOn,
  cilTags,
  cilTask,
  cilTerminal,
  cilThumbDown,
  cilThumbUp,
  cilTrash,
  cilUnderline,
  cilUser,
  cilUserFemale,
  cilUserFollow,
  cilUserUnfollow,
  cilVideogame,
  cilVolumeHigh,
  cilVolumeLow,
  cilVolumeOff,
  cilZoom,
} from '@coreui/icons';

import { signet } from './signet';
import { logo } from './logo';

export const iconSubset = {
  ...brandSet,
  cifBr,
  cifEs,
  cifFr,
  cifIn,
  cifPl,
  cifUs,
  cilAccountLogout,
  cilActionUndo,
  cilAlignCenter,
  cilAlignLeft,
  cilAlignRight,
  cilApplications,
  cilApplicationsSettings,
  cilArrowBottom,
  cilArrowRight,
  cilArrowTop,
  cilBadge,
  cilBasket,
  cilBell,
  cilBold,
  cilBook,
  cilBookmark,
  cilBug,
  cilCalculator,
  cilCalendar,
  cilCast,
  cilChart,
  cilChartPie,
  cilCheck,
  cilChevronCircleLeftAlt,
  cilChevronDoubleLeft,
  cilChevronDoubleRight,
  cilChevronLeft,
  cilChevronRight,
  cilCloudDownload,
  cilCode,
  cilCommentSquare,
  cilContrast,
  cilCreditCard,
  cilCursor,
  cilDelete,
  cilDescription,
  cilDollar,
  cilDrop,
  cilEnvelopeClosed,
  cilEnvelopeOpen,
  cilFeaturedPlaylist,
  cilFile,
  cilGamepad,
  cilGrid,
  cilHeart,
  cilHome,
  cilImage,
  cilInbox,
  cilIndentDecrease,
  cilIndentIncrease,
  cilInfo,
  cilItalic,
  cilJustifyCenter,
  cilLanguage,
  cilLaptop,
  cilLayers,
  cilLibraryAdd,
  cilLink,
  cilLinkBroken,
  cilList,
  cilListNumbered,
  cilLocationPin,
  cilLockLocked,
  cilMagnifyingGlass,
  cilMap,
  cilMediaPlay,
  cilMediaRecord,
  cilMenu,
  cilMobile,
  cilMoon,
  cilMovie,
  cilNoteAdd,
  cilNotes,
  cilOptions,
  cilPaperclip,
  cilPaperPlane,
  cilPen,
  cilPencil,
  cilPeople,
  cilPowerStandby,
  cilPrint,
  cilPuzzle,
  cilReportSlash,
  cilRouter,
  cilSave,
  cilSearch,
  cilSend,
  cilSettings,
  cilShare,
  cilShareAll,
  cilShareBoxed,
  cilShieldAlt,
  cilSpeech,
  cilSpeedometer,
  cilSpreadsheet,
  cilStar,
  cilSun,
  cilSync,
  cilToggleOff,
  cilToggleOn,
  cilTags,
  cilTask,
  cilTerminal,
  cilThumbDown,
  cilThumbUp,
  cilTrash,
  cilUnderline,
  cilUser,
  cilUserFemale,
  cilUserFollow,
  cilUserUnfollow,
  cilVideogame,
  cilVolumeHigh,
  cilVolumeLow,
  cilVolumeOff,
  cilZoom,
  logo,
  signet
};

export enum IconSubset {
  cilAccountLogout = 'cilAccountLogout',
  cilActionUndo = 'cilActionUndo',
  cilAlignCenter = 'cilAlignCenter',
  cilAlignLeft = 'cilAlignLeft',
  cilAlignRight = 'cilAlignRight',
  cilApplications = 'cilApplications',
  cilApplicationsSettings = 'cilApplicationsSettings',
  cilArrowBottom = 'cilArrowBottom',
  cilArrowRight = 'cilArrowRight',
  cilArrowTop = 'cilArrowTop',
  cilBadge = 'cilBadge',
  cilBasket = 'cilBasket',
  cilBell = 'cilBell',
  cilBold = 'cilBold',
  cilBook = 'cilBook',
  cilBookmark = 'cilBookmark',
  cilBug = 'cilBug',
  cilCalculator = 'cilCalculator',
  cilCalendar = 'cilCalendar',
  cilCast = 'cilCast',
  cilChart = 'cilChart',
  cilChartPie = 'cilChartPie',
  cilCheck = 'cilCheck',
  cilChevronCircleLeftAlt = 'cilChevronCircleLeftAlt',
  cilChevronDoubleLeft = 'cilChevronDoubleLeft',
  cilChevronDoubleRight = 'cilChevronDoubleRight',
  cilChevronLeft = 'cilChevronLeft',
  cilChevronRight = 'cilChevronRight',
  cilCloudDownload = 'cilCloudDownload',
  cilCode = 'cilCode',
  cilCommentSquare = 'cilCommentSquare',
  cilContrast = 'cilContrast',
  cilCreditCard = 'cilCreditCard',
  cilCursor = 'cilCursor',
  cilDelete = 'cilDelete',
  cilDescription = 'cilDescription',
  cilDollar = 'cilDollar',
  cilDrop = 'cilDrop',
  cilEnvelopeClosed = 'cilEnvelopeClosed',
  cilEnvelopeOpen = 'cilEnvelopeOpen',
  cilFeaturedPlaylist = 'cilFeaturedPlaylist',
  cilFile = 'cilFile',
  cilGamepad = 'cilGamepad',
  cilGrid = 'cilGrid',
  cilHeart = 'cilHeart',
  cilHome = 'cilHome',
  cilImage = 'cilImage',
  cilInbox = 'cilInbox',
  cilIndentDecrease = 'cilIndentDecrease',
  cilIndentIncrease = 'cilIndentIncrease',
  cilInfo = 'cilInfo',
  cilItalic = 'cilItalic',
  cilJustifyCenter = 'cilJustifyCenter',
  cilLanguage = 'cilLanguage',
  cilLaptop = 'cilLaptop',
  cilLayers = 'cilLayers',
  cilLibraryAdd = 'cilLibraryAdd',
  cilLink = 'cilLink',
  cilLinkBroken = 'cilLinkBroken',
  cilList = 'cilList',
  cilListNumbered = 'cilListNumbered',
  cilLocationPin = 'cilLocationPin',
  cilLockLocked = 'cilLockLocked',
  cilMagnifyingGlass = 'cilMagnifyingGlass',
  cilMap = 'cilMap',
  cilMediaPlay = 'cilMediaPlay',
  cilMediaRecord = 'cilMediaRecord',
  cilMenu = 'cilMenu',
  cilMobile = 'cilMobile',
  cilMoon = 'cilMoon',
  cilMovie = 'cilMovie',
  cilNoteAdd = 'cilNoteAdd',
  cilNotes = 'cilNotes',
  cilOptions = 'cilOptions',
  cilPaperclip = 'cilPaperclip',
  cilPaperPlane = 'cilPaperPlane',
  cilPen = 'cilPen',
  cilPencil = 'cilPencil',
  cilPeople = 'cilPeople',
  cilPowerStandby = 'cilPowerStandby',
  cilPrint = 'cilPrint',
  cilPuzzle = 'cilPuzzle',
  cilReportSlash = 'cilReportSlash',
  cilRouter = 'cilRouter',
  cilSave = 'cilSave',
  cilSearch = 'cilSearch',
  cilSend = 'cilSend',
  cilSettings = 'cilSettings',
  cilShare = 'cilShare',
  cilShareAll = 'cilShareAll',
  cilShareBoxed = 'cilShareBoxed',
  cilShieldAlt = 'cilShieldAlt',
  cilSpeech = 'cilSpeech',
  cilSpeedometer = 'cilSpeedometer',
  cilSpreadsheet = 'cilSpreadsheet',
  cilStar = 'cilStar',
  cilSun = 'cilSun',
  cilSync = 'cilSync',
  cilToggleOff = 'cilToggleOff',
  cilToggleOn = 'cilToggleOn',
  cilTags = 'cilTags',
  cilTask = 'cilTask',
  cilTerminal = 'cilTerminal',
  cilThumbDown = 'cilThumbDown',
  cilThumbUp = 'cilThumbUp',
  cilTrash = 'cilTrash',
  cilUnderline = 'cilUnderline',
  cilUser = 'cilUser',
  cilUserFemale = 'cilUserFemale',
  cilUserFollow = 'cilUserFollow',
  cilUserUnfollow = 'cilUserUnfollow',
  cilVideogame = 'cilVideogame',
  cilVolumeHigh = 'cilVolumeHigh',
  cilVolumeLow = 'cilVolumeLow',
  cilVolumeOff = 'cilVolumeOff',
  cilZoom = 'cilZoom',
  logo = 'logo',
  signet = 'signet'
}
